# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "wolfi-demo/java-maven"
version = "0.0.1"
name = "Demo Wolfi Base Java Maven Buildpack"
homepage = "https://github.com/patflynn/chainguard-stack"


# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.samples.stacks.alpine"

[[stacks]]
id = "wolfi-base-stack"
